spring:
  cloud:
    config:
      server:
        git:
          uri: http://github.com/WixBe/books_author_microservices-config
          clone-on-start: true
logging:
  pattern:
    console: "%msg%n"
server:
  port: 8888